### ISSUE TITLE
Error running elogger tests

### ISSUE THREAD

**Issue by dragonpiper** [viant/endly#35]
I'm trying to run the elogger tests via `endly -r=run` but it fails in the log validation stage for some reason.

`[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                             stdin]
rm -f /opt/elogger/logs/*
[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                            stdout]

[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                            stdout]

[run[app]run|regresion[Prepare]                                                                               exec.run]
[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                             stdin]
cd /
[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                            stdout]

[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                             stdin]
rm -f /opt/elogger/logs/*
[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                            stdout]

[run[app]run|regresion[Prepare]exec.run 127.0.0.1:22                                                            stdout]

[run[app]run|regresion[Prepare]                                                                   validator/log.listen]
[run[app]run|regresion[Prepare]validator/log.listen unsupported scheme /opt/elogger/logs at validator/log.listen error]
[run[app]run|regresion[Prepare]validator/log.listen regresion_Prepare: unsupported scheme /opt/elogger/logs at v error]
regresion_Prepare: unsupported scheme /opt/elogger/logs at validator/log.listen at workflow.run
[run[app]run|regresion[Prepare]validator/log.listen run: regresion_Prepare: unsupported scheme /opt/elogger/logs error]
run: regresion_Prepare: unsupported scheme /opt/elogger/logs at validator/log.listen at workflow.run
[STATUS: FAILED `

**Comment by adranwit** [comment]
Can you share your log.listen request

endly -s='validator/log' -a=listen (some valid exaples)

The problem is storage service that expect resource protocol, (i.e. file:///, scp:// etc...)
Endly uses toolbox/url/resource.go which will dynamically expand  /path as  file://path, so there is no need to provide proto, in log  validator listen, it looks like in one place the init resource were not used but original unexpanded URL, I have applied potential patch to master,

**Comment by dragonpiper** [comment]
`ServiceRequest: *log.ListenRequest
Description:  check for log changesExample 1:  log listen request
@listen.json
{
        "FrequencyMs": 500,
        "Source": {
                "Credentials": "${env.HOME}/.secret/localhost.json",
                "URL": "scp://127.0.0.1/opt/elogger/logs/"
        },
        "Types": [
                {
                        "Format": "json",
                        "Inclusion": "/event1/",
                        "IndexRegExpr": "\"EventID\":\"([^\"]+)\"",
                        "Mask": "elog*.log",
                        "Name": "event1"
                }
        ]
}
@listen.yaml
FrequencyMs: 500
Source:
  Credentials: ${env.HOME}/.secret/localhost.json
  URL: scp://127.0.0.1/opt/elogger/logs/
Types:
- Format: json
  Inclusion: /event1/
  IndexRegExpr: '"EventID":"([^"]+)"'
  Mask: elog*.log
  Name: event1

Empty request:
{
        "FrequencyMs": 0,
        "Source": {
                "URL": "",
                "Credentials": "",
                "Cache": "",
                "CacheExpiryMs": 0
        },
        "Types": [
                {
                        "Name": "",
                        "Format": "",
                        "Mask": "",
                        "Exclusion": "",
                        "Inclusion": "",
                        "IndexRegExpr": "",
                        "UDF": ""
                }
        ]
}

*log.ListenRequest
-------------------------------------------------
|       Name|         Type|Required| Description|
-------------------------------------------------
|FrequencyMs|int          |false   |            |
-------------------------------------------------
|Source     |*url.Resource|true    |log location|
-------------------------------------------------
|Types      |[]*log.Type  |true    |log types   |
-------------------------------------------------
url.Resource
-------------------------------------------------------------------------
|         Name|  Type|Required|                              Description|
-------------------------------------------------------------------------
|CacheExpiryMs|int   |false   |                                         |
-------------------------------------------------------------------------
|URL          |string|true    |resource URL or relative or absolute path|
-------------------------------------------------------------------------
|Credentials  |string|false   |credentials file                         |
-------------------------------------------------------------------------
|Cache        |string|false   |local cache path                         |
-------------------------------------------------------------------------
*log.Type
------------------------------------------------------------------------------------------------------------
|        Name|  Type|Required|                                                                  Description|
------------------------------------------------------------------------------------------------------------
|Name        |string|true    |log type name  |
------------------------------------------------------------------------------------------------------------
|Format      |string|false   |log format  |
------------------------------------------------------------------------------------------------------------
|Mask        |string|false   |expected log file mast  |
------------------------------------------------------------------------------------------------------------
|Exclusion   |string|false   |if specified, exclusion fragment can not match log record  |
------------------------------------------------------------------------------------------------------------
|Inclusion   |string|false   |if specified, inclusion fragment must match log record  |
------------------------------------------------------------------------------------------------------------
|IndexRegExpr|string|false   |provide expression for indexing log messages, in this case position based  |
|            |      |        |logging will not apply  |
------------------------------------------------------------------------------------------------------------
|UDF         |string|false   |registered user defined function to transform content file before applying  |
|            |      |        |validation i,e decompress  |
------------------------------------------------------------------------------------------------------------
Response: *log.ListenResponse
Empty response:
{
        "Meta": {
                "": {
                        "Source": {
                                "URL": "",
                                "Credentials": "",
                                "Cache": "",
                                "CacheExpiryMs": 0
                        },
                        "LogType": {
                                "Name": "",
                                "Format": "",
                                "Mask": "",
                                "Exclusion": "",
                                "Inclusion": "",
                                "IndexRegExpr": "",
                                "UDF": ""
                        },
                        "LogFiles": {
                                "": {
                                        "URL": "",
                                        "Content": "",
                                        "Name": "",
                                        "Format": "",
                                        "Mask": "",
                                        "Exclusion": "",
                                        "Inclusion": "",
                                        "IndexRegExpr": "",
                                        "UDF": "",
                                        "ProcessingState": {
                                                "Line": 0,
                                                "Position": 0
                                        },
                                        "LastModified": "0001-01-01T00:00:00Z",
                                        "Size": 0,
                                        "Records": [
                                                {
                                                        "URL": "",
                                                        "Number": 0,
                                                        "Line": ""
                                                }
                                        ],
                                        "IndexedRecords": {
                                                "": {
                                                        "URL": "",
                                                        "Number": 0,
                                                        "Line": ""
                                                }
                                        },
                                        "Mutex": {}
                                }
                        }
                }
        }
}

*log.ListenResponse
-----------------------------------------
|Name|         Type|Required|Description|
-----------------------------------------
|Meta|log.TypesMeta|false   |           |
-----------------------------------------
*log.TypeMeta
----------------------------------------------------
|    Name|                Type|Required|Description|
----------------------------------------------------
|Source  |*url.Resource       |false   |           |
----------------------------------------------------
|LogType |*log.Type           |false   |           |
----------------------------------------------------
|LogFiles|map[string]*log.File|false   |           |
----------------------------------------------------
url.Resource
-------------------------------------------------------------------------
|         Name|  Type|Required|                              Description|
-------------------------------------------------------------------------
|URL          |string|true    |resource URL or relative or absolute path|
-------------------------------------------------------------------------
|Credentials  |string|false   |credentials file                         |
-------------------------------------------------------------------------
|Cache        |string|false   |local cache path                         |
-------------------------------------------------------------------------
|CacheExpiryMs|int   |false   |                                         |
-------------------------------------------------------------------------
log.Type
------------------------------------------------------------------------------------------------------------
|        Name|  Type|Required|                                                                  Description|
------------------------------------------------------------------------------------------------------------
|Exclusion   |string|false   |if specified, exclusion fragment can not match log record  |
------------------------------------------------------------------------------------------------------------
|Inclusion   |string|false   |if specified, inclusion fragment must match log record  |
------------------------------------------------------------------------------------------------------------
|IndexRegExpr|string|false   |provide expression for indexing log messages, in this case position based  |
|            |      |        |logging will not apply  |
------------------------------------------------------------------------------------------------------------
|UDF         |string|false   |registered user defined function to transform content file before applying  |
|            |      |        |validation i,e decompress  |
------------------------------------------------------------------------------------------------------------
|Name        |string|true    |log type name  |
------------------------------------------------------------------------------------------------------------
|Format      |string|false   |log format  |
------------------------------------------------------------------------------------------------------------
|Mask        |string|false   |expected log file mast  |
------------------------------------------------------------------------------------------------------------
*log.File
------------------------------------------------------------------------------------------------------------
|           Name|                  Type|Required|                                               Description|
------------------------------------------------------------------------------------------------------------
|URL            |string                |false   |  |
------------------------------------------------------------------------------------------------------------
|Content        |string                |false   |  |
------------------------------------------------------------------------------------------------------------
|IndexedRecords |map[string]*log.Record|false   |  |
------------------------------------------------------------------------------------------------------------
|Name           |string                |false   |  |
------------------------------------------------------------------------------------------------------------
|Format         |string                |false   |log format  |
------------------------------------------------------------------------------------------------------------
|Inclusion      |string                |false   |if specified, inclusion fragment must match log record  |
------------------------------------------------------------------------------------------------------------
|Records        |[]*log.Record         |false   |  |
------------------------------------------------------------------------------------------------------------
|Size           |int                   |false   |  |
------------------------------------------------------------------------------------------------------------
|Mask           |string                |false   |expected log file mast  |
------------------------------------------------------------------------------------------------------------
|UDF            |string                |false   |registered user defined function to transform content file|
|               |                      |        |before applying validation i,e decompress  |
------------------------------------------------------------------------------------------------------------
|ProcessingState|*log.ProcessingState  |false   |  |
------------------------------------------------------------------------------------------------------------
|Mutex          |*sync.RWMutex         |false   |  |
------------------------------------------------------------------------------------------------------------
|Exclusion      |string                |false   |if specified, exclusion fragment can not match log record |
------------------------------------------------------------------------------------------------------------
|IndexRegExpr   |string                |false   |provide expression for indexing log messages, in this case|
|               |                      |        |position based logging will not apply  |
------------------------------------------------------------------------------------------------------------
|LastModified   |time.Time             |false   |  |
------------------------------------------------------------------------------------------------------------
*log.Record
------------------------------------
|  Name|  Type|Required|Description|
------------------------------------
|URL   |string|false   |           |
------------------------------------
|Number|int   |false   |           |
------------------------------------
|Line  |string|false   |           |
------------------------------------
log.ProcessingState
------------------------------------
|    Name|Type|Required|Description|
------------------------------------
|Line    |int |false   |           |
------------------------------------
|Position|int |false   |           |
------------------------------------
sync.RWMutex
--------------------------------
|Name|Type|Required|Description|
--------------------------------`

**Comment by adranwit** [comment]
can you provide output of the following:
 endly -f=yaml -p  regression/regression.csv 

it should print your regression workflow model.

are you using e2e test project generator (endly -g)
are you using  github.com/viant/endly/example/rt/elogger/e2e ?

The latter one works for me in the autogenerated project I have addressed one glitch,

In either case please use the latest updated endly 0.18.0 and let me know if the issue has been resolved

Check also fully functional inline workflow example 
https://github.com/viant/endly/tree/master/testing/log

endly -s='validator/log' -a=listen give you example req/res for various endly services and supported action, it works  as CLI documentation.

**Comment by adranwit** [comment]
Channel info update: gophers.slack.com #endly

**Comment by adranwit** [comment]
Just to follow up, are you still seeing any issue with testing logger?
If there is no response I will close this issue within 48 hours.
