### ISSUE TITLE
understanding regression tests

### ISSUE THREAD

**Issue by dragonpiper** [viant/endly#36]
is there an irc channel they you guys are active in for discussing questions / issues ? 

also in the elogger pipeline , what is being executed at the following stage ?

  test:
    action: run
    name: regresion
    tasks: "*"

is run a built in service or does it referencing something else and what is regression referencing ?

**Comment by adranwit** [comment]
You can use the slack #endly channel for any question, disucssion

To check what task are defined by a workflow you can use the following
endly -t='?' -w=regression/regression.csv 

you can also run endly -d  switch, in that case logs directory is with all execution details

action has the following format: service:action,  if service: is empty workflow service is used, 

action:run is equal to action:workflow.run
