### ISSUE TITLE
Tar archive for osx seems corrupted

### ISSUE THREAD

**Issue by Moncefmd** [viant/endly#57]
Tried opening the archive available in the release section but neither tar nor macos recognizes that it is a valid tar.gz.

```
➜  Downloads    tar -xvzf endly_osx_0.44.0.tar.gz

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by adranwit** [comment]
let me build 45 version,

**Comment by adranwit** [comment]
Address in version 0.45.0, 
Also publish new docker image
-  endly/endly:latest-ubuntu16.04
-  endly/endly:0.45.0-ubuntu16.04

**Comment by adranwit** [comment]
Address in version 0.45.0,
Also publish new docker image
