### ISSUE TITLE
Build from source documentation needs to be updated

### ISSUE THREAD

**Issue by shaneHowearth** [viant/endly#67]
Trying to build endly with an older version of go produces
```
$ go build
build github.com/viant/endly/endly: cannot load embed: malformed module path "embed": missing dot in first path element
```

Embed was first released in 1.16 (I think) https://golang.org/doc/go1.16#library-embed
So, endly can no longer be built by versions of Go older than 1.16 (I get that versions older than that may not be supported, but the documentation says 1.11 or later, which is now incorrect)

**Comment by adranwit** [comment]
Updated afs dependency so it should build with go1.11

**Comment by shaneHowearth** [comment]
Thanks, tested with 1.13.15 linux/amd64 and am now able to build

**Comment by adranwit** [comment]
Thanks for raising the issue
