### ISSUE TITLE
checkError not failing

### ISSUE THREAD

**Issue by pja237** [viant/endly#71]
Hello gentlemen,

in the docs there is an example of a workflow failing based on command exit code with checkError:

```
pipeline:
  package:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - whoami
      - /bin/false
```

When i try it out, everything seems to pass without errors, is this a bug or an i misinterpreting the docs?

```
[x[package]                                                                                                                                                                                              exec.run]
[x[package]exec.run pja@localhost:22                                                                                                                                                                        stdin]
whoami
[x[package]exec.run pja@localhost:22                                                                                                                                                                       stdout]
pja
[x[package]exec.run pja@localhost:22                                                                                                                                                                        stdin]
/bin/false
[x[package]exec.run pja@localhost:22                                                                                                                                                                       stdout]

[STATUS: SUCCESS   
```

**Comment by adranwit** [comment]
Hi, Endly uses echo $? to determine executed command status code, and report error based on that, 
Hope it helps,

**Comment by pja237** [comment]
Hey, sorry not to update this ticket sooner, but i've managed to uncover the root cause for this (similar to #70).
Just to give you guys kudos for this tool, we love it and have put it to use in our [project](https://github.com/CLIP-HPC/goslmailer) successfully.

The problems we had boiled down to 3 issues, i'll copy/paste them from our installation guide in case someone runs into them.

Known caveats:

* redhat/centos: must have lsb_release binary installed, package: `redhat-lsb-core`
* ubuntu 22: `set enable-bracketed-paste off` present in ~/.inputrc
* maybe/maybe not, depends if you see failed tests: `export TERM=dumb` in ~/.bashrc :)

Thanks again for the great work guys 👍
